Added test programs
bobbimanners/Applecorn pull request #276
Opened 2023-01-20 13:33 UTC by jgharston

2023-01-20 17:31 UTC, bobbimanners requested changes
Hi Jonathan,

Could you rebase this on the latest code?  You are trying to merge in an older `auxmem.chario.s`.

Thanks :)

Bobbi

2023-01-21 22:19 UTC, jgharston commented
Hmm. Git says there's nothing to Sync, but also says chario is different. I'll have to try again on a proper PC.

2023-01-22 18:44 UTC, bobbimanners commented
I have similar problems in that GitHub says there are 'no conflicts' when there plainly are.  Not sure what that is all about tbh.

2023-01-22 21:32 UTC, bobbimanners approved these changes

2023-01-22 21:32 UTC, merged